# Generated by Django 3.1.1 on 2023-08-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_paymentintent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentIntent',
        ),
    ]
